{{- if .Values.continuum.cloudGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuum-platform.cloud-gateway.fullname" . }}
  labels:
    {{- include "continuum-platform.componentLabels" (dict "context" $ "component" "cloud-gateway" "extra" .Values.continuum.cloudGateway.labels.service) | nindent 4 }}
  {{- with (include "continuum-platform.componentAnnotations" (dict "context" $ "extra" .Values.continuum.cloudGateway.annotations.service)) }}
  annotations:
    {{- nindent 4 . }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.continuum.cloudGateway.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: cloud-gateway
    {{- include "continuum-platform.selectorLabels" . | nindent 4 }}
{{- end }}
