{{- if .Values.continuum.clusterManager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "continuum-platform.cluster-manager.fullname" . }}-workbench-manager
  namespace: {{ .Values.continuum.clusterManager.workbench.namespace }}
  labels:
    {{- include "continuum-platform.componentLabels" (dict "context" $ "component" "cluster-manager" "extra" .Values.continuum.clusterManager.labels.roleBinding) | nindent 4 }}
  {{- with (include "continuum-platform.componentAnnotations" (dict "context" $ "extra" .Values.continuum.clusterManager.annotations.roleBinding)) }}
  annotations:
    {{- nindent 4 . }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "continuum-platform.cluster-manager.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "continuum-platform.cluster-manager.fullname" . }}-workbench-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }}

