{{- if and .Values.continuum.clusterManager.enabled .Values.continuum.clusterManager.workbench.middleware.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: workbench-strip-context-path
  namespace: {{ .Values.continuum.clusterManager.workbench.namespace }}
  labels:
    {{- include "continuum-platform.componentLabels" (dict "context" $ "component" "cluster-manager" "extra" .Values.continuum.clusterManager.labels.middleware) | nindent 4 }}
  {{- with (include "continuum-platform.componentAnnotations" (dict "context" $ "extra" .Values.continuum.clusterManager.annotations.middleware)) }}
  annotations:
    {{- nindent 4 . }}
  {{- end }}
spec:
  stripPrefix:
    prefixes:
      {{- range .Values.continuum.clusterManager.workbench.middleware.stripPrefixes }}
      - {{ . | quote }}
      {{- end }}
{{- end }}
