{{- if .Values.continuum.orchestrationService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "continuum-platform.orchestration-service.fullname" . }}
  labels:
    {{- include "continuum-platform.componentLabels" (dict "context" $ "component" "orchestration-service" "extra" .Values.continuum.orchestrationService.labels.service) | nindent 4 }}
  {{- with (include "continuum-platform.componentAnnotations" (dict "context" $ "extra" .Values.continuum.orchestrationService.annotations.service)) }}
  annotations:
    {{- nindent 4 . }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.continuum.orchestrationService.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: orchestration-service
    {{- include "continuum-platform.selectorLabels" . | nindent 4 }}
{{- end }}
