{{/* ---- PostgreSQL Secret ---- */}}
{{- if not .Values.continuum.secrets.existingPostgresqlSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "continuum-platform.postgresql.secretName" . }}
  labels:
    app.kubernetes.io/component: postgresql
    {{- include "continuum-platform.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.continuum.secrets.postgresql.username | default "continuum" | b64enc | quote }}
  password: {{ required "secrets.postgresql.password is required when no existingPostgresqlSecret is set" .Values.continuum.secrets.postgresql.password | b64enc | quote }}
{{- end }}
---
{{/* ---- MinIO Secret ---- */}}
{{- if not .Values.continuum.secrets.existingMinioSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "continuum-platform.minio.secretName" . }}
  labels:
    app.kubernetes.io/component: minio
    {{- include "continuum-platform.labels" . | nindent 4 }}
type: Opaque
data:
  root-user: {{ .Values.continuum.secrets.minio.rootUser | default "minioadmin" | b64enc | quote }}
  root-password: {{ required "secrets.minio.rootPassword is required when no existingMinioSecret is set" .Values.continuum.secrets.minio.rootPassword | b64enc | quote }}
{{- end }}
